#############################################################################
# Makefile for building: 10122
# Generated by qmake (3.1) (Qt 5.12.3)
# Project:  10122.pro
# Template: app
# Command: /opt/Qt/5.12.3/gcc_64/bin/qmake -o Makefile 10122.pro
#############################################################################

MAKEFILE      = Makefile

EQ            = =

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_NETWORK_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -O2 -Wall -W -D_REENTRANT -fPIC $(DEFINES)
CXXFLAGS      = -pipe -O2 -Wall -W -D_REENTRANT -fPIC $(DEFINES)
QT_DIR=/opt/Qt/5.12.3/gcc_64
INCPATH       = -I. -I$(QT_DIR)/include -I$(QT_DIR)/include/QtNetwork -I$(QT_DIR)/include/QtCore -I. #-I$(QT_DIR)/mkspecs/linux-g++
QMAKE         = $(QT_DIR)/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
QINSTALL      = $(QT_DIR)/bin/qmake -install qinstall
QINSTALL_PROGRAM = $(QT_DIR)/bin/qmake -install qinstall -exe
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = 101221.0.0
DISTDIR = /home/user/da/pro/hmi1/10122/.tmp/101221.0.0
LINK          = g++
LFLAGS        = -Wl,-O1 -Wl,-rpath,$(QT_DIR)/lib
LIBS          = $(SUBLIBS) -L$(QT_DIR)/lib -lQt5Network -lQt5Core -lpthread   
AR            = ar cqs
RANLIB        = 
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = gameplay.cpp \
		main.cpp moc_gameplay.cpp
OBJECTS       = gameplay.o \
		main.o \
		moc_gameplay.o
#DIST          = $(QT_DIR)/mkspecs/features/spec_pre.prf \
#		$(QT_DIR)/mkspecs/common/unix.conf \
#		$(QT_DIR)/mkspecs/common/linux.conf \
#		$(QT_DIR)/mkspecs/common/sanitize.conf \
#		$(QT_DIR)/mkspecs/common/gcc-base.conf \
#		$(QT_DIR)/mkspecs/common/gcc-base-unix.conf \
#		$(QT_DIR)/mkspecs/common/g++-base.conf \
#		$(QT_DIR)/mkspecs/common/g++-unix.conf \
#		$(QT_DIR)/mkspecs/qconfig.pri \
#		$(QT_DIR)/mkspecs/modules/qt_lib_3danimation.pri \
#		$(QT_DIR)/mkspecs/modules/qt_lib_3danimation_private.pri \
#		$(QT_DIR)/mkspecs/modules/qt_lib_3dcore.pri \
#		$(QT_DIR)/mkspecs/modules/qt_lib_3dcore_private.pri \
#		$(QT_DIR)/mkspecs/modules/qt_lib_3dextras.pri \
#		$(QT_DIR)/mkspecs/modules/qt_lib_3dextras_private.pri \
#		$(QT_DIR)/mkspecs/modules/qt_lib_3dinput.pri \
#		$(QT_DIR)/mkspecs/modules/qt_lib_3dinput_private.pri \
#		$(QT_DIR)/mkspecs/modules/qt_lib_3dlogic.pri \
#		$(QT_DIR)/mkspecs/modules/qt_lib_3dlogic_private.pri \
#		$(QT_DIR)/mkspecs/modules/qt_lib_3dquick.pri \
#		$(QT_DIR)/mkspecs/modules/qt_lib_3dquick_private.pri \
#		$(QT_DIR)/mkspecs/modules/qt_lib_3dquickanimation.pri \
#		$(QT_DIR)/mkspecs/modules/qt_lib_3dquickanimation_private.pri \
#		$(QT_DIR)/mkspecs/modules/qt_lib_3dquickextras.pri \
#		$(QT_DIR)/mkspecs/modules/qt_lib_3dquickextras_private.pri \
#		$(QT_DIR)/mkspecs/modules/qt_lib_3dquickinput.pri \
#		$(QT_DIR)/mkspecs/modules/qt_lib_3dquickinput_private.pri \
#		$(QT_DIR)/mkspecs/modules/qt_lib_3dquickrender.pri \
#		$(QT_DIR)/mkspecs/modules/qt_lib_3dquickrender_private.pri \
#		$(QT_DIR)/mkspecs/modules/qt_lib_3dquickscene2d.pri \
#		$(QT_DIR)/mkspecs/modules/qt_lib_3dquickscene2d_private.pri \
#		$(QT_DIR)/mkspecs/modules/qt_lib_3drender.pri \
#		$(QT_DIR)/mkspecs/modules/qt_lib_3drender_private.pri \
#		$(QT_DIR)/mkspecs/modules/qt_lib_accessibility_support_private.pri \
#		$(QT_DIR)/mkspecs/modules/qt_lib_bluetooth.pri \
#		$(QT_DIR)/mkspecs/modules/qt_lib_bluetooth_private.pri \
#		$(QT_DIR)/mkspecs/modules/qt_lib_bootstrap_private.pri \
#		$(QT_DIR)/mkspecs/modules/qt_lib_charts.pri \
#		$(QT_DIR)/mkspecs/modules/qt_lib_charts_private.pri \
#		$(QT_DIR)/mkspecs/modules/qt_lib_concurrent.pri \
#		$(QT_DIR)/mkspecs/modules/qt_lib_concurrent_private.pri \
#		$(QT_DIR)/mkspecs/modules/qt_lib_core.pri \
#		$(QT_DIR)/mkspecs/modules/qt_lib_core_private.pri \
#		$(QT_DIR)/mkspecs/modules/qt_lib_datavisualization.pri \
#		$(QT_DIR)/mkspecs/modules/qt_lib_datavisualization_private.pri \
#		$(QT_DIR)/mkspecs/modules/qt_lib_dbus.pri \
#		$(QT_DIR)/mkspecs/modules/qt_lib_dbus_private.pri \
#		$(QT_DIR)/mkspecs/modules/qt_lib_designer.pri \
#		$(QT_DIR)/mkspecs/modules/qt_lib_designer_private.pri \
#		$(QT_DIR)/mkspecs/modules/qt_lib_designercomponents_private.pri \
#		$(QT_DIR)/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
#		$(QT_DIR)/mkspecs/modules/qt_lib_edid_support_private.pri \
#		$(QT_DIR)/mkspecs/modules/qt_lib_egl_support_private.pri \
#		$(QT_DIR)/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
#		$(QT_DIR)/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
#		$(QT_DIR)/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
#		$(QT_DIR)/mkspecs/modules/qt_lib_fb_support_private.pri \
#		$(QT_DIR)/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
#		$(QT_DIR)/mkspecs/modules/qt_lib_gamepad.pri \
#		$(QT_DIR)/mkspecs/modules/qt_lib_gamepad_private.pri \
#		$(QT_DIR)/mkspecs/modules/qt_lib_glx_support_private.pri \
#		$(QT_DIR)/mkspecs/modules/qt_lib_gui.pri \
#		$(QT_DIR)/mkspecs/modules/qt_lib_gui_private.pri \
#		$(QT_DIR)/mkspecs/modules/qt_lib_help.pri \
#		$(QT_DIR)/mkspecs/modules/qt_lib_help_private.pri \
#		$(QT_DIR)/mkspecs/modules/qt_lib_input_support_private.pri \
#		$(QT_DIR)/mkspecs/modules/qt_lib_kms_support_private.pri \
#		$(QT_DIR)/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri \
#		$(QT_DIR)/mkspecs/modules/qt_lib_location.pri \
#		$(QT_DIR)/mkspecs/modules/qt_lib_location_private.pri \
#		$(QT_DIR)/mkspecs/modules/qt_lib_multimedia.pri \
#		$(QT_DIR)/mkspecs/modules/qt_lib_multimedia_private.pri \
#		$(QT_DIR)/mkspecs/modules/qt_lib_multimediagsttools_private.pri \
#		$(QT_DIR)/mkspecs/modules/qt_lib_multimediawidgets.pri \
#		$(QT_DIR)/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
#		$(QT_DIR)/mkspecs/modules/qt_lib_network.pri \
#		$(QT_DIR)/mkspecs/modules/qt_lib_network_private.pri \
#		$(QT_DIR)/mkspecs/modules/qt_lib_networkauth.pri \
#		$(QT_DIR)/mkspecs/modules/qt_lib_networkauth_private.pri \
#		$(QT_DIR)/mkspecs/modules/qt_lib_nfc.pri \
#		$(QT_DIR)/mkspecs/modules/qt_lib_nfc_private.pri \
#		$(QT_DIR)/mkspecs/modules/qt_lib_opengl.pri \
#		$(QT_DIR)/mkspecs/modules/qt_lib_opengl_private.pri \
#		$(QT_DIR)/mkspecs/modules/qt_lib_openglextensions.pri \
#		$(QT_DIR)/mkspecs/modules/qt_lib_openglextensions_private.pri \
#		$(QT_DIR)/mkspecs/modules/qt_lib_packetprotocol_private.pri \
#		$(QT_DIR)/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
#		$(QT_DIR)/mkspecs/modules/qt_lib_positioning.pri \
#		$(QT_DIR)/mkspecs/modules/qt_lib_positioning_private.pri \
#		$(QT_DIR)/mkspecs/modules/qt_lib_positioningquick.pri \
#		$(QT_DIR)/mkspecs/modules/qt_lib_positioningquick_private.pri \
#		$(QT_DIR)/mkspecs/modules/qt_lib_printsupport.pri \
#		$(QT_DIR)/mkspecs/modules/qt_lib_printsupport_private.pri \
#		$(QT_DIR)/mkspecs/modules/qt_lib_qml.pri \
#		$(QT_DIR)/mkspecs/modules/qt_lib_qml_private.pri \
#		$(QT_DIR)/mkspecs/modules/qt_lib_qmldebug_private.pri \
#		$(QT_DIR)/mkspecs/modules/qt_lib_qmldevtools_private.pri \
#		$(QT_DIR)/mkspecs/modules/qt_lib_qmltest.pri \
#		$(QT_DIR)/mkspecs/modules/qt_lib_qmltest_private.pri \
#		$(QT_DIR)/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
#		$(QT_DIR)/mkspecs/modules/qt_lib_quick.pri \
#		$(QT_DIR)/mkspecs/modules/qt_lib_quick_private.pri \
#		$(QT_DIR)/mkspecs/modules/qt_lib_quickcontrols2.pri \
#		$(QT_DIR)/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
#		$(QT_DIR)/mkspecs/modules/qt_lib_quickparticles_private.pri \
#		$(QT_DIR)/mkspecs/modules/qt_lib_quickshapes_private.pri \
#		$(QT_DIR)/mkspecs/modules/qt_lib_quicktemplates2.pri \
#		$(QT_DIR)/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
#		$(QT_DIR)/mkspecs/modules/qt_lib_quickwidgets.pri \
#		$(QT_DIR)/mkspecs/modules/qt_lib_quickwidgets_private.pri \
#		$(QT_DIR)/mkspecs/modules/qt_lib_remoteobjects.pri \
#		$(QT_DIR)/mkspecs/modules/qt_lib_remoteobjects_private.pri \
#		$(QT_DIR)/mkspecs/modules/qt_lib_repparser.pri \
#		$(QT_DIR)/mkspecs/modules/qt_lib_repparser_private.pri \
#		$(QT_DIR)/mkspecs/modules/qt_lib_scxml.pri \
#		$(QT_DIR)/mkspecs/modules/qt_lib_scxml_private.pri \
#		$(QT_DIR)/mkspecs/modules/qt_lib_sensors.pri \
#		$(QT_DIR)/mkspecs/modules/qt_lib_sensors_private.pri \
#		$(QT_DIR)/mkspecs/modules/qt_lib_serialbus.pri \
#		$(QT_DIR)/mkspecs/modules/qt_lib_serialbus_private.pri \
#		$(QT_DIR)/mkspecs/modules/qt_lib_serialport.pri \
#		$(QT_DIR)/mkspecs/modules/qt_lib_serialport_private.pri \
#		$(QT_DIR)/mkspecs/modules/qt_lib_service_support_private.pri \
#		$(QT_DIR)/mkspecs/modules/qt_lib_sql.pri \
#		$(QT_DIR)/mkspecs/modules/qt_lib_sql_private.pri \
#		$(QT_DIR)/mkspecs/modules/qt_lib_svg.pri \
#		$(QT_DIR)/mkspecs/modules/qt_lib_svg_private.pri \
#		$(QT_DIR)/mkspecs/modules/qt_lib_testlib.pri \
#		$(QT_DIR)/mkspecs/modules/qt_lib_testlib_private.pri \
#		$(QT_DIR)/mkspecs/modules/qt_lib_texttospeech.pri \
#		$(QT_DIR)/mkspecs/modules/qt_lib_texttospeech_private.pri \
#		$(QT_DIR)/mkspecs/modules/qt_lib_theme_support_private.pri \
#		$(QT_DIR)/mkspecs/modules/qt_lib_uiplugin.pri \
#		$(QT_DIR)/mkspecs/modules/qt_lib_uitools.pri \
#		$(QT_DIR)/mkspecs/modules/qt_lib_uitools_private.pri \
#		$(QT_DIR)/mkspecs/modules/qt_lib_waylandclient.pri \
#		$(QT_DIR)/mkspecs/modules/qt_lib_waylandclient_private.pri \
#		$(QT_DIR)/mkspecs/modules/qt_lib_waylandcompositor.pri \
#		$(QT_DIR)/mkspecs/modules/qt_lib_waylandcompositor_private.pri \
#		$(QT_DIR)/mkspecs/modules/qt_lib_webchannel.pri \
#		$(QT_DIR)/mkspecs/modules/qt_lib_webchannel_private.pri \
#		$(QT_DIR)/mkspecs/modules/qt_lib_webengine.pri \
#		$(QT_DIR)/mkspecs/modules/qt_lib_webengine_private.pri \
#		$(QT_DIR)/mkspecs/modules/qt_lib_webenginecore.pri \
#		$(QT_DIR)/mkspecs/modules/qt_lib_webenginecore_private.pri \
#		$(QT_DIR)/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri \
#		$(QT_DIR)/mkspecs/modules/qt_lib_webenginewidgets.pri \
#		$(QT_DIR)/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
#		$(QT_DIR)/mkspecs/modules/qt_lib_websockets.pri \
#		$(QT_DIR)/mkspecs/modules/qt_lib_websockets_private.pri \
#		$(QT_DIR)/mkspecs/modules/qt_lib_webview.pri \
#		$(QT_DIR)/mkspecs/modules/qt_lib_webview_private.pri \
#		$(QT_DIR)/mkspecs/modules/qt_lib_widgets.pri \
#		$(QT_DIR)/mkspecs/modules/qt_lib_widgets_private.pri \
#		$(QT_DIR)/mkspecs/modules/qt_lib_x11extras.pri \
#		$(QT_DIR)/mkspecs/modules/qt_lib_x11extras_private.pri \
#		$(QT_DIR)/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
#		$(QT_DIR)/mkspecs/modules/qt_lib_xml.pri \
#		$(QT_DIR)/mkspecs/modules/qt_lib_xml_private.pri \
#		$(QT_DIR)/mkspecs/modules/qt_lib_xmlpatterns.pri \
#		$(QT_DIR)/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
#		$(QT_DIR)/mkspecs/features/qt_functions.prf \
#		$(QT_DIR)/mkspecs/features/qt_config.prf \
#		$(QT_DIR)/mkspecs/linux-g++/qmake.conf \
#		$(QT_DIR)/mkspecs/features/spec_post.prf \
#		.qmake.stash \
#		$(QT_DIR)/mkspecs/features/exclusive_builds.prf \
#		$(QT_DIR)/mkspecs/features/toolchain.prf \
#		$(QT_DIR)/mkspecs/features/default_pre.prf \
#		$(QT_DIR)/mkspecs/features/resolve_config.prf \
#		$(QT_DIR)/mkspecs/features/default_post.prf \
#		$(QT_DIR)/mkspecs/features/warn_on.prf \
#		$(QT_DIR)/mkspecs/features/qt.prf \
#		$(QT_DIR)/mkspecs/features/resources.prf \
#		$(QT_DIR)/mkspecs/features/moc.prf \
#		$(QT_DIR)/mkspecs/features/unix/thread.prf \
#		$(QT_DIR)/mkspecs/features/qmake_use.prf \
#		$(QT_DIR)/mkspecs/features/file_copies.prf \
#		$(QT_DIR)/mkspecs/features/testcase_targets.prf \
#		$(QT_DIR)/mkspecs/features/exceptions.prf \
#		$(QT_DIR)/mkspecs/features/yacc.prf \
#		$(QT_DIR)/mkspecs/features/lex.prf \
#		10122.pro gameplay.h gameplay.cpp \
#		main.cpp
QMAKE_TARGET  = 10122
DESTDIR       = 
TARGET        = 10122


first: all
####### Build rules

10122:  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

#Makefile: 10122.pro \
#		$(QT_DIR)/mkspecs/linux-g++/qmake.conf $(QT_DIR)/mkspecs/features/spec_pre.prf \
#		$(QT_DIR)/mkspecs/common/unix.conf \
#		$(QT_DIR)/mkspecs/common/linux.conf \
#		$(QT_DIR)/mkspecs/common/sanitize.conf \
#		$(QT_DIR)/mkspecs/common/gcc-base.conf \
#		$(QT_DIR)/mkspecs/common/gcc-base-unix.conf \
#		$(QT_DIR)/mkspecs/common/g++-base.conf \
#		$(QT_DIR)/mkspecs/common/g++-unix.conf \
#		$(QT_DIR)/mkspecs/qconfig.pri \
#		$(QT_DIR)/mkspecs/modules/qt_lib_3danimation.pri \
#		$(QT_DIR)/mkspecs/modules/qt_lib_3danimation_private.pri \
#		$(QT_DIR)/mkspecs/modules/qt_lib_3dcore.pri \
#		$(QT_DIR)/mkspecs/modules/qt_lib_3dcore_private.pri \
#		$(QT_DIR)/mkspecs/modules/qt_lib_3dextras.pri \
#		$(QT_DIR)/mkspecs/modules/qt_lib_3dextras_private.pri \
#		$(QT_DIR)/mkspecs/modules/qt_lib_3dinput.pri \
#		$(QT_DIR)/mkspecs/modules/qt_lib_3dinput_private.pri \
#		$(QT_DIR)/mkspecs/modules/qt_lib_3dlogic.pri \
#		$(QT_DIR)/mkspecs/modules/qt_lib_3dlogic_private.pri \
#		$(QT_DIR)/mkspecs/modules/qt_lib_3dquick.pri \
#		$(QT_DIR)/mkspecs/modules/qt_lib_3dquick_private.pri \
#		$(QT_DIR)/mkspecs/modules/qt_lib_3dquickanimation.pri \
#		$(QT_DIR)/mkspecs/modules/qt_lib_3dquickanimation_private.pri \
#		$(QT_DIR)/mkspecs/modules/qt_lib_3dquickextras.pri \
#		$(QT_DIR)/mkspecs/modules/qt_lib_3dquickextras_private.pri \
#		$(QT_DIR)/mkspecs/modules/qt_lib_3dquickinput.pri \
#		$(QT_DIR)/mkspecs/modules/qt_lib_3dquickinput_private.pri \
#		$(QT_DIR)/mkspecs/modules/qt_lib_3dquickrender.pri \
#		$(QT_DIR)/mkspecs/modules/qt_lib_3dquickrender_private.pri \
#		$(QT_DIR)/mkspecs/modules/qt_lib_3dquickscene2d.pri \
#		$(QT_DIR)/mkspecs/modules/qt_lib_3dquickscene2d_private.pri \
#		$(QT_DIR)/mkspecs/modules/qt_lib_3drender.pri \
#		$(QT_DIR)/mkspecs/modules/qt_lib_3drender_private.pri \
#		$(QT_DIR)/mkspecs/modules/qt_lib_accessibility_support_private.pri \
#		$(QT_DIR)/mkspecs/modules/qt_lib_bluetooth.pri \
#		$(QT_DIR)/mkspecs/modules/qt_lib_bluetooth_private.pri \
#		$(QT_DIR)/mkspecs/modules/qt_lib_bootstrap_private.pri \
#		$(QT_DIR)/mkspecs/modules/qt_lib_charts.pri \
#		$(QT_DIR)/mkspecs/modules/qt_lib_charts_private.pri \
#		$(QT_DIR)/mkspecs/modules/qt_lib_concurrent.pri \
#		$(QT_DIR)/mkspecs/modules/qt_lib_concurrent_private.pri \
#		$(QT_DIR)/mkspecs/modules/qt_lib_core.pri \
#		$(QT_DIR)/mkspecs/modules/qt_lib_core_private.pri \
#		$(QT_DIR)/mkspecs/modules/qt_lib_datavisualization.pri \
#		$(QT_DIR)/mkspecs/modules/qt_lib_datavisualization_private.pri \
#		$(QT_DIR)/mkspecs/modules/qt_lib_dbus.pri \
#		$(QT_DIR)/mkspecs/modules/qt_lib_dbus_private.pri \
#		$(QT_DIR)/mkspecs/modules/qt_lib_designer.pri \
#		$(QT_DIR)/mkspecs/modules/qt_lib_designer_private.pri \
#		$(QT_DIR)/mkspecs/modules/qt_lib_designercomponents_private.pri \
#		$(QT_DIR)/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
#		$(QT_DIR)/mkspecs/modules/qt_lib_edid_support_private.pri \
#		$(QT_DIR)/mkspecs/modules/qt_lib_egl_support_private.pri \
#		$(QT_DIR)/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
#		$(QT_DIR)/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
#		$(QT_DIR)/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
#		$(QT_DIR)/mkspecs/modules/qt_lib_fb_support_private.pri \
#		$(QT_DIR)/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
#		$(QT_DIR)/mkspecs/modules/qt_lib_gamepad.pri \
#		$(QT_DIR)/mkspecs/modules/qt_lib_gamepad_private.pri \
#		$(QT_DIR)/mkspecs/modules/qt_lib_glx_support_private.pri \
#		$(QT_DIR)/mkspecs/modules/qt_lib_gui.pri \
#		$(QT_DIR)/mkspecs/modules/qt_lib_gui_private.pri \
#		$(QT_DIR)/mkspecs/modules/qt_lib_help.pri \
#		$(QT_DIR)/mkspecs/modules/qt_lib_help_private.pri \
#		$(QT_DIR)/mkspecs/modules/qt_lib_input_support_private.pri \
#		$(QT_DIR)/mkspecs/modules/qt_lib_kms_support_private.pri \
#		$(QT_DIR)/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri \
#		$(QT_DIR)/mkspecs/modules/qt_lib_location.pri \
#		$(QT_DIR)/mkspecs/modules/qt_lib_location_private.pri \
#		$(QT_DIR)/mkspecs/modules/qt_lib_multimedia.pri \
#		$(QT_DIR)/mkspecs/modules/qt_lib_multimedia_private.pri \
#		$(QT_DIR)/mkspecs/modules/qt_lib_multimediagsttools_private.pri \
#		$(QT_DIR)/mkspecs/modules/qt_lib_multimediawidgets.pri \
#		$(QT_DIR)/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
#		$(QT_DIR)/mkspecs/modules/qt_lib_network.pri \
#		$(QT_DIR)/mkspecs/modules/qt_lib_network_private.pri \
#		$(QT_DIR)/mkspecs/modules/qt_lib_networkauth.pri \
#		$(QT_DIR)/mkspecs/modules/qt_lib_networkauth_private.pri \
#		$(QT_DIR)/mkspecs/modules/qt_lib_nfc.pri \
#		$(QT_DIR)/mkspecs/modules/qt_lib_nfc_private.pri \
#		$(QT_DIR)/mkspecs/modules/qt_lib_opengl.pri \
#		$(QT_DIR)/mkspecs/modules/qt_lib_opengl_private.pri \
#		$(QT_DIR)/mkspecs/modules/qt_lib_openglextensions.pri \
#		$(QT_DIR)/mkspecs/modules/qt_lib_openglextensions_private.pri \
#		$(QT_DIR)/mkspecs/modules/qt_lib_packetprotocol_private.pri \
#		$(QT_DIR)/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
#		$(QT_DIR)/mkspecs/modules/qt_lib_positioning.pri \
#		$(QT_DIR)/mkspecs/modules/qt_lib_positioning_private.pri \
#		$(QT_DIR)/mkspecs/modules/qt_lib_positioningquick.pri \
#		$(QT_DIR)/mkspecs/modules/qt_lib_positioningquick_private.pri \
#		$(QT_DIR)/mkspecs/modules/qt_lib_printsupport.pri \
#		$(QT_DIR)/mkspecs/modules/qt_lib_printsupport_private.pri \
#		$(QT_DIR)/mkspecs/modules/qt_lib_qml.pri \
#		$(QT_DIR)/mkspecs/modules/qt_lib_qml_private.pri \
#		$(QT_DIR)/mkspecs/modules/qt_lib_qmldebug_private.pri \
#		$(QT_DIR)/mkspecs/modules/qt_lib_qmldevtools_private.pri \
#		$(QT_DIR)/mkspecs/modules/qt_lib_qmltest.pri \
#		$(QT_DIR)/mkspecs/modules/qt_lib_qmltest_private.pri \
#		$(QT_DIR)/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
#		$(QT_DIR)/mkspecs/modules/qt_lib_quick.pri \
#		$(QT_DIR)/mkspecs/modules/qt_lib_quick_private.pri \
#		$(QT_DIR)/mkspecs/modules/qt_lib_quickcontrols2.pri \
#		$(QT_DIR)/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
#		$(QT_DIR)/mkspecs/modules/qt_lib_quickparticles_private.pri \
#		$(QT_DIR)/mkspecs/modules/qt_lib_quickshapes_private.pri \
#		$(QT_DIR)/mkspecs/modules/qt_lib_quicktemplates2.pri \
#		$(QT_DIR)/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
#		$(QT_DIR)/mkspecs/modules/qt_lib_quickwidgets.pri \
#		$(QT_DIR)/mkspecs/modules/qt_lib_quickwidgets_private.pri \
#		$(QT_DIR)/mkspecs/modules/qt_lib_remoteobjects.pri \
#		$(QT_DIR)/mkspecs/modules/qt_lib_remoteobjects_private.pri \
#		$(QT_DIR)/mkspecs/modules/qt_lib_repparser.pri \
#		$(QT_DIR)/mkspecs/modules/qt_lib_repparser_private.pri \
#		$(QT_DIR)/mkspecs/modules/qt_lib_scxml.pri \
#		$(QT_DIR)/mkspecs/modules/qt_lib_scxml_private.pri \
#		$(QT_DIR)/mkspecs/modules/qt_lib_sensors.pri \
#		$(QT_DIR)/mkspecs/modules/qt_lib_sensors_private.pri \
#		$(QT_DIR)/mkspecs/modules/qt_lib_serialbus.pri \
#		$(QT_DIR)/mkspecs/modules/qt_lib_serialbus_private.pri \
#		$(QT_DIR)/mkspecs/modules/qt_lib_serialport.pri \
#		$(QT_DIR)/mkspecs/modules/qt_lib_serialport_private.pri \
#		$(QT_DIR)/mkspecs/modules/qt_lib_service_support_private.pri \
#		$(QT_DIR)/mkspecs/modules/qt_lib_sql.pri \
#		$(QT_DIR)/mkspecs/modules/qt_lib_sql_private.pri \
#		$(QT_DIR)/mkspecs/modules/qt_lib_svg.pri \
#		$(QT_DIR)/mkspecs/modules/qt_lib_svg_private.pri \
#		$(QT_DIR)/mkspecs/modules/qt_lib_testlib.pri \
#		$(QT_DIR)/mkspecs/modules/qt_lib_testlib_private.pri \
#		$(QT_DIR)/mkspecs/modules/qt_lib_texttospeech.pri \
#		$(QT_DIR)/mkspecs/modules/qt_lib_texttospeech_private.pri \
#		$(QT_DIR)/mkspecs/modules/qt_lib_theme_support_private.pri \
#		$(QT_DIR)/mkspecs/modules/qt_lib_uiplugin.pri \
#		$(QT_DIR)/mkspecs/modules/qt_lib_uitools.pri \
#		$(QT_DIR)/mkspecs/modules/qt_lib_uitools_private.pri \
#		$(QT_DIR)/mkspecs/modules/qt_lib_waylandclient.pri \
#		$(QT_DIR)/mkspecs/modules/qt_lib_waylandclient_private.pri \
#		$(QT_DIR)/mkspecs/modules/qt_lib_waylandcompositor.pri \
#		$(QT_DIR)/mkspecs/modules/qt_lib_waylandcompositor_private.pri \
#		$(QT_DIR)/mkspecs/modules/qt_lib_webchannel.pri \
#		$(QT_DIR)/mkspecs/modules/qt_lib_webchannel_private.pri \
#		$(QT_DIR)/mkspecs/modules/qt_lib_webengine.pri \
#		$(QT_DIR)/mkspecs/modules/qt_lib_webengine_private.pri \
#		$(QT_DIR)/mkspecs/modules/qt_lib_webenginecore.pri \
#		$(QT_DIR)/mkspecs/modules/qt_lib_webenginecore_private.pri \
#		$(QT_DIR)/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri \
#		$(QT_DIR)/mkspecs/modules/qt_lib_webenginewidgets.pri \
#		$(QT_DIR)/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
#		$(QT_DIR)/mkspecs/modules/qt_lib_websockets.pri \
#		$(QT_DIR)/mkspecs/modules/qt_lib_websockets_private.pri \
#		$(QT_DIR)/mkspecs/modules/qt_lib_webview.pri \
#		$(QT_DIR)/mkspecs/modules/qt_lib_webview_private.pri \
#		$(QT_DIR)/mkspecs/modules/qt_lib_widgets.pri \
#		$(QT_DIR)/mkspecs/modules/qt_lib_widgets_private.pri \
#		$(QT_DIR)/mkspecs/modules/qt_lib_x11extras.pri \
#		$(QT_DIR)/mkspecs/modules/qt_lib_x11extras_private.pri \
#		$(QT_DIR)/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
#		$(QT_DIR)/mkspecs/modules/qt_lib_xml.pri \
#		$(QT_DIR)/mkspecs/modules/qt_lib_xml_private.pri \
#		$(QT_DIR)/mkspecs/modules/qt_lib_xmlpatterns.pri \
#		$(QT_DIR)/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
#		$(QT_DIR)/mkspecs/features/qt_functions.prf \
#		$(QT_DIR)/mkspecs/features/qt_config.prf \
#		$(QT_DIR)/mkspecs/linux-g++/qmake.conf \
#		$(QT_DIR)/mkspecs/features/spec_post.prf \
#		.qmake.stash \
#		$(QT_DIR)/mkspecs/features/exclusive_builds.prf \
#		$(QT_DIR)/mkspecs/features/toolchain.prf \
#		$(QT_DIR)/mkspecs/features/default_pre.prf \
#		$(QT_DIR)/mkspecs/features/resolve_config.prf \
#		$(QT_DIR)/mkspecs/features/default_post.prf \
#		$(QT_DIR)/mkspecs/features/warn_on.prf \
#		$(QT_DIR)/mkspecs/features/qt.prf \
#		$(QT_DIR)/mkspecs/features/resources.prf \
#		$(QT_DIR)/mkspecs/features/moc.prf \
#		$(QT_DIR)/mkspecs/features/unix/thread.prf \
#		$(QT_DIR)/mkspecs/features/qmake_use.prf \
#		$(QT_DIR)/mkspecs/features/file_copies.prf \
#		$(QT_DIR)/mkspecs/features/testcase_targets.prf \
#		$(QT_DIR)/mkspecs/features/exceptions.prf \
#		$(QT_DIR)/mkspecs/features/yacc.prf \
#		$(QT_DIR)/mkspecs/features/lex.prf \
#		10122.pro \
#		$(QT_DIR)/lib/libQt5Network.prl \
#		$(QT_DIR)/lib/libQt5Core.prl
#	$(QMAKE) -o Makefile 10122.pro
#$(QT_DIR)/mkspecs/features/spec_pre.prf:
#$(QT_DIR)/mkspecs/common/unix.conf:
#$(QT_DIR)/mkspecs/common/linux.conf:
#$(QT_DIR)/mkspecs/common/sanitize.conf:
#$(QT_DIR)/mkspecs/common/gcc-base.conf:
#$(QT_DIR)/mkspecs/common/gcc-base-unix.conf:
#$(QT_DIR)/mkspecs/common/g++-base.conf:
#$(QT_DIR)/mkspecs/common/g++-unix.conf:
#$(QT_DIR)/mkspecs/qconfig.pri:
#$(QT_DIR)/mkspecs/modules/qt_lib_3danimation.pri:
#$(QT_DIR)/mkspecs/modules/qt_lib_3danimation_private.pri:
#$(QT_DIR)/mkspecs/modules/qt_lib_3dcore.pri:
#$(QT_DIR)/mkspecs/modules/qt_lib_3dcore_private.pri:
#/opt/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_3dextras.pri:
#/opt/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_3dextras_private.pri:
#/opt/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_3dinput.pri:
#/opt/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_3dinput_private.pri:
#/opt/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_3dlogic.pri:
#/opt/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_3dlogic_private.pri:
#/opt/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_3dquick.pri:
#/opt/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_3dquick_private.pri:
#/opt/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_3dquickanimation.pri:
#/opt/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_3dquickanimation_private.pri:
#/opt/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_3dquickextras.pri:
#/opt/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_3dquickextras_private.pri:
#/opt/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_3dquickinput.pri:
#/opt/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_3dquickinput_private.pri:
#/opt/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_3dquickrender.pri:
#/opt/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_3dquickrender_private.pri:
#/opt/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_3dquickscene2d.pri:
#/opt/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_3dquickscene2d_private.pri:
#/opt/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_3drender.pri:
#/opt/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_3drender_private.pri:
#/opt/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_accessibility_support_private.pri:
#/opt/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_bluetooth.pri:
#/opt/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_bluetooth_private.pri:
#/opt/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_bootstrap_private.pri:
#/opt/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_charts.pri:
#/opt/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_charts_private.pri:
#/opt/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_concurrent.pri:
#/opt/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_concurrent_private.pri:
#/opt/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_core.pri:
#/opt/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_core_private.pri:
#/opt/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_datavisualization.pri:
#/opt/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_datavisualization_private.pri:
#/opt/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_dbus.pri:
#/opt/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_dbus_private.pri:
#/opt/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_designer.pri:
#/opt/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_designer_private.pri:
#/opt/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_designercomponents_private.pri:
#/opt/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
#/opt/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_edid_support_private.pri:
#/opt/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_egl_support_private.pri:
#/opt/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri:
#/opt/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri:
#/opt/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri:
#/opt/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_fb_support_private.pri:
#/opt/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_fontdatabase_support_private.pri:
#/opt/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_gamepad.pri:
#/opt/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_gamepad_private.pri:
#/opt/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_glx_support_private.pri:
#/opt/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_gui.pri:
#/opt/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_gui_private.pri:
#/opt/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_help.pri:
#/opt/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_help_private.pri:
#/opt/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_input_support_private.pri:
#/opt/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_kms_support_private.pri:
#/opt/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri:
#/opt/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_location.pri:
#/opt/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_location_private.pri:
#/opt/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_multimedia.pri:
#/opt/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_multimedia_private.pri:
#/opt/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_multimediagsttools_private.pri:
#/opt/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_multimediawidgets.pri:
#/opt/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
#/opt/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_network.pri:
#/opt/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_network_private.pri:
#/opt/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_networkauth.pri:
#/opt/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_networkauth_private.pri:
#/opt/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_nfc.pri:
#/opt/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_nfc_private.pri:
#/opt/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_opengl.pri:
#/opt/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_opengl_private.pri:
#/opt/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_openglextensions.pri:
#/opt/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_openglextensions_private.pri:
#/opt/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_packetprotocol_private.pri:
#/opt/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_platformcompositor_support_private.pri:
#/opt/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_positioning.pri:
#/opt/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_positioning_private.pri:
#/opt/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_positioningquick.pri:
#/opt/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_positioningquick_private.pri:
#/opt/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_printsupport.pri:
#/opt/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_printsupport_private.pri:
#/opt/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_qml.pri:
#/opt/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_qml_private.pri:
#/opt/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_qmldebug_private.pri:
#/opt/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_qmldevtools_private.pri:
#/opt/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_qmltest.pri:
#/opt/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_qmltest_private.pri:
#/opt/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
#/opt/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_quick.pri:
#/opt/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_quick_private.pri:
#/opt/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_quickcontrols2.pri:
#/opt/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri:
#/opt/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_quickparticles_private.pri:
#/opt/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_quickshapes_private.pri:
#/opt/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_quicktemplates2.pri:
#/opt/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri:
#/opt/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_quickwidgets.pri:
#/opt/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_quickwidgets_private.pri:
#/opt/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_remoteobjects.pri:
#/opt/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_remoteobjects_private.pri:
#/opt/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_repparser.pri:
#/opt/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_repparser_private.pri:
#/opt/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_scxml.pri:
#/opt/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_scxml_private.pri:
#/opt/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_sensors.pri:
#/opt/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_sensors_private.pri:
#/opt/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_serialbus.pri:
#/opt/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_serialbus_private.pri:
#/opt/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_serialport.pri:
#/opt/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_serialport_private.pri:
#/opt/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_service_support_private.pri:
#/opt/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_sql.pri:
#/opt/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_sql_private.pri:
#/opt/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_svg.pri:
#/opt/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_svg_private.pri:
#/opt/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_testlib.pri:
#/opt/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_testlib_private.pri:
#/opt/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_texttospeech.pri:
#/opt/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_texttospeech_private.pri:
#/opt/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_theme_support_private.pri:
#/opt/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_uiplugin.pri:
#/opt/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_uitools.pri:
#/opt/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_uitools_private.pri:
#/opt/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_waylandclient.pri:
#/opt/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_waylandclient_private.pri:
#/opt/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_waylandcompositor.pri:
#/opt/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_waylandcompositor_private.pri:
#/opt/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_webchannel.pri:
#/opt/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_webchannel_private.pri:
#/opt/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_webengine.pri:
#/opt/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_webengine_private.pri:
#/opt/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_webenginecore.pri:
#/opt/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_webenginecore_private.pri:
#/opt/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri:
#/opt/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_webenginewidgets.pri:
#/opt/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri:
#/opt/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_websockets.pri:
#/opt/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_websockets_private.pri:
#/opt/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_webview.pri:
#/opt/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_webview_private.pri:
#/opt/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_widgets.pri:
#/opt/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_widgets_private.pri:
#/opt/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_x11extras.pri:
#/opt/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_x11extras_private.pri:
#/opt/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri:
#/opt/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_xml.pri:
#/opt/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_xml_private.pri:
#/opt/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_xmlpatterns.pri:
#/opt/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
#/opt/Qt/5.12.3/gcc_64/mkspecs/features/qt_functions.prf:
#/opt/Qt/5.12.3/gcc_64/mkspecs/features/qt_config.prf:
#/opt/Qt/5.12.3/gcc_64/mkspecs/linux-g++/qmake.conf:
#/opt/Qt/5.12.3/gcc_64/mkspecs/features/spec_post.prf:
#.qmake.stash:
#/opt/Qt/5.12.3/gcc_64/mkspecs/features/exclusive_builds.prf:
#/opt/Qt/5.12.3/gcc_64/mkspecs/features/toolchain.prf:
#/opt/Qt/5.12.3/gcc_64/mkspecs/features/default_pre.prf:
#/opt/Qt/5.12.3/gcc_64/mkspecs/features/resolve_config.prf:
#/opt/Qt/5.12.3/gcc_64/mkspecs/features/default_post.prf:
#/opt/Qt/5.12.3/gcc_64/mkspecs/features/warn_on.prf:
#/opt/Qt/5.12.3/gcc_64/mkspecs/features/qt.prf:
#/opt/Qt/5.12.3/gcc_64/mkspecs/features/resources.prf:
#/opt/Qt/5.12.3/gcc_64/mkspecs/features/moc.prf:
#/opt/Qt/5.12.3/gcc_64/mkspecs/features/unix/thread.prf:
#/opt/Qt/5.12.3/gcc_64/mkspecs/features/qmake_use.prf:
#/opt/Qt/5.12.3/gcc_64/mkspecs/features/file_copies.prf:
#/opt/Qt/5.12.3/gcc_64/mkspecs/features/testcase_targets.prf:
#/opt/Qt/5.12.3/gcc_64/mkspecs/features/exceptions.prf:
#/opt/Qt/5.12.3/gcc_64/mkspecs/features/yacc.prf:
#/opt/Qt/5.12.3/gcc_64/mkspecs/features/lex.prf:
10122.pro:
$(QT_DIR)/lib/libQt5Network.prl:
$(QT_DIR)/lib/libQt5Core.prl:
qmake: FORCE
	@$(QMAKE) -o Makefile 10122.pro

qmake_all: FORCE


all: Makefile 10122

#dist: distdir FORCE
#	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

#distdir: FORCE
#	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
#	#$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
#	$(COPY_FILE) --parents $(QT_DIR)/mkspecs/features/data/dummy.cpp $(DISTDIR)/
#	$(COPY_FILE) --parents gameplay.h $(DISTDIR)/
#	$(COPY_FILE) --parents gameplay.cpp main.cpp $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_objc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_objc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_moc_predefs_make_all: moc_predefs.h
compiler_moc_predefs_clean:
	-$(DEL_FILE) moc_predefs.h
#moc_predefs.h: $(QT_DIR)/mkspecs/features/data/dummy.cpp
#	g++ -pipe -O2 -Wall -W -dM -E -o moc_predefs.h $(QT_DIR)/mkspecs/features/data/dummy.cpp

compiler_moc_header_make_all: moc_gameplay.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_gameplay.cpp
#moc_gameplay.cpp: gameplay.h \
#		$(QT_DIR)/include/QtCore/QObject \
#		$(QT_DIR)/include/QtCore/qobject.h \
#		$(QT_DIR)/include/QtCore/qobjectdefs.h \
#		$(QT_DIR)/include/QtCore/qnamespace.h \
#		$(QT_DIR)/include/QtCore/qglobal.h \
#		$(QT_DIR)/include/QtCore/qconfig-bootstrapped.h \
#		$(QT_DIR)/include/QtCore/qconfig.h \
#		$(QT_DIR)/include/QtCore/qtcore-config.h \
#		$(QT_DIR)/include/QtCore/qsystemdetection.h \
#		$(QT_DIR)/include/QtCore/qprocessordetection.h \
#		$(QT_DIR)/include/QtCore/qcompilerdetection.h \
#		$(QT_DIR)/include/QtCore/qtypeinfo.h \
#		$(QT_DIR)/include/QtCore/qsysinfo.h \
#		$(QT_DIR)/include/QtCore/qlogging.h \
#		$(QT_DIR)/include/QtCore/qflags.h \
#		$(QT_DIR)/include/QtCore/qatomic.h \
#		$(QT_DIR)/include/QtCore/qbasicatomic.h \
#		$(QT_DIR)/include/QtCore/qatomic_bootstrap.h \
#		$(QT_DIR)/include/QtCore/qgenericatomic.h \
#		$(QT_DIR)/include/QtCore/qatomic_cxx11.h \
#		$(QT_DIR)/include/QtCore/qatomic_msvc.h \
#		$(QT_DIR)/include/QtCore/qglobalstatic.h \
#		$(QT_DIR)/include/QtCore/qmutex.h \
#		$(QT_DIR)/include/QtCore/qnumeric.h \
#		$(QT_DIR)/include/QtCore/qversiontagging.h \
#		$(QT_DIR)/include/QtCore/qobjectdefs_impl.h \
#		$(QT_DIR)/include/QtCore/qstring.h \
#		$(QT_DIR)/include/QtCore/qchar.h \
#		$(QT_DIR)/include/QtCore/qbytearray.h \
#		$(QT_DIR)/include/QtCore/qrefcount.h \
#		$(QT_DIR)/include/QtCore/qarraydata.h \
#		$(QT_DIR)/include/QtCore/qstringliteral.h \
#		$(QT_DIR)/include/QtCore/qstringalgorithms.h \
#		$(QT_DIR)/include/QtCore/qstringview.h \
#		$(QT_DIR)/include/QtCore/qstringbuilder.h \
#		$(QT_DIR)/include/QtCore/qlist.h \
#		$(QT_DIR)/include/QtCore/qalgorithms.h \
#		$(QT_DIR)/include/QtCore/qiterator.h \
#		$(QT_DIR)/include/QtCore/qhashfunctions.h \
#		$(QT_DIR)/include/QtCore/qpair.h \
#		$(QT_DIR)/include/QtCore/qbytearraylist.h \
#		$(QT_DIR)/include/QtCore/qstringlist.h \
#		$(QT_DIR)/include/QtCore/qregexp.h \
#		$(QT_DIR)/include/QtCore/qstringmatcher.h \
#		$(QT_DIR)/include/QtCore/qcoreevent.h \
#		$(QT_DIR)/include/QtCore/qscopedpointer.h \
#		$(QT_DIR)/include/QtCore/qmetatype.h \
#		$(QT_DIR)/include/QtCore/qvarlengtharray.h \
#		$(QT_DIR)/include/QtCore/qcontainerfwd.h \
#		$(QT_DIR)/include/QtCore/qobject_impl.h \
#		$(QT_DIR)/include/QtNetwork/QUdpSocket \
#		$(QT_DIR)/include/QtNetwork/qudpsocket.h \
#		$(QT_DIR)/include/QtNetwork/qtnetworkglobal.h \
#		$(QT_DIR)/include/QtNetwork/qtnetwork-config.h \
#		$(QT_DIR)/include/QtNetwork/qabstractsocket.h \
#		$(QT_DIR)/include/QtCore/qiodevice.h \
#		$(QT_DIR)/include/QtCore/qdebug.h \
#		$(QT_DIR)/include/QtCore/qhash.h \
#		$(QT_DIR)/include/QtCore/qmap.h \
#		$(QT_DIR)/include/QtCore/qtextstream.h \
#		$(QT_DIR)/include/QtCore/qlocale.h \
#		$(QT_DIR)/include/QtCore/qvariant.h \
#		$(QT_DIR)/include/QtCore/qshareddata.h \
#		$(QT_DIR)/include/QtCore/qvector.h \
#		$(QT_DIR)/include/QtCore/qpoint.h \
#		$(QT_DIR)/include/QtCore/qset.h \
#		$(QT_DIR)/include/QtCore/qcontiguouscache.h \
#		$(QT_DIR)/include/QtCore/qsharedpointer.h \
#		$(QT_DIR)/include/QtCore/qsharedpointer_impl.h \
#		$(QT_DIR)/include/QtNetwork/qhostaddress.h \
#		moc_predefs.h \
#		$(QT_DIR)/bin/moc
#	$(QT_DIR)/bin/moc $(DEFINES) --include /home/user/da/pro/hmi1/10122/moc_predefs.h -I$(QT_DIR)/mkspecs/linux-g++ -I/home/user/da/pro/hmi1/10122 -I$(QT_DIR)/include -I$(QT_DIR)/include/QtNetwork -I$(QT_DIR)/include/QtCore -I/usr/include/c++/7 -I/usr/include/x86_64-linux-gnu/c++/7 -I/usr/include/c++/7/backward -I/usr/lib/gcc/x86_64-linux-gnu/7/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/7/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include gameplay.h -o moc_gameplay.cpp

compiler_moc_objc_header_make_all:
compiler_moc_objc_header_clean:
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_predefs_clean compiler_moc_header_clean 

####### Compile

gameplay.o: gameplay.cpp gameplay.h \
		$(QT_DIR)/include/QtCore/QObject \
		$(QT_DIR)/include/QtCore/qobject.h \
		$(QT_DIR)/include/QtCore/qobjectdefs.h \
		$(QT_DIR)/include/QtCore/qnamespace.h \
		$(QT_DIR)/include/QtCore/qglobal.h \
		$(QT_DIR)/include/QtCore/qconfig-bootstrapped.h \
		$(QT_DIR)/include/QtCore/qconfig.h \
		$(QT_DIR)/include/QtCore/qtcore-config.h \
		$(QT_DIR)/include/QtCore/qsystemdetection.h \
		$(QT_DIR)/include/QtCore/qprocessordetection.h \
		$(QT_DIR)/include/QtCore/qcompilerdetection.h \
		$(QT_DIR)/include/QtCore/qtypeinfo.h \
		$(QT_DIR)/include/QtCore/qsysinfo.h \
		$(QT_DIR)/include/QtCore/qlogging.h \
		$(QT_DIR)/include/QtCore/qflags.h \
		$(QT_DIR)/include/QtCore/qatomic.h \
		$(QT_DIR)/include/QtCore/qbasicatomic.h \
		$(QT_DIR)/include/QtCore/qatomic_bootstrap.h \
		$(QT_DIR)/include/QtCore/qgenericatomic.h \
		$(QT_DIR)/include/QtCore/qatomic_cxx11.h \
		$(QT_DIR)/include/QtCore/qatomic_msvc.h \
		$(QT_DIR)/include/QtCore/qglobalstatic.h \
		$(QT_DIR)/include/QtCore/qmutex.h \
		$(QT_DIR)/include/QtCore/qnumeric.h \
		$(QT_DIR)/include/QtCore/qversiontagging.h \
		$(QT_DIR)/include/QtCore/qobjectdefs_impl.h \
		$(QT_DIR)/include/QtCore/qstring.h \
		$(QT_DIR)/include/QtCore/qchar.h \
		$(QT_DIR)/include/QtCore/qbytearray.h \
		$(QT_DIR)/include/QtCore/qrefcount.h \
		$(QT_DIR)/include/QtCore/qarraydata.h \
		$(QT_DIR)/include/QtCore/qstringliteral.h \
		$(QT_DIR)/include/QtCore/qstringalgorithms.h \
		$(QT_DIR)/include/QtCore/qstringview.h \
		$(QT_DIR)/include/QtCore/qstringbuilder.h \
		$(QT_DIR)/include/QtCore/qlist.h \
		$(QT_DIR)/include/QtCore/qalgorithms.h \
		$(QT_DIR)/include/QtCore/qiterator.h \
		$(QT_DIR)/include/QtCore/qhashfunctions.h \
		$(QT_DIR)/include/QtCore/qpair.h \
		$(QT_DIR)/include/QtCore/qbytearraylist.h \
		$(QT_DIR)/include/QtCore/qstringlist.h \
		$(QT_DIR)/include/QtCore/qregexp.h \
		$(QT_DIR)/include/QtCore/qstringmatcher.h \
		$(QT_DIR)/include/QtCore/qcoreevent.h \
		$(QT_DIR)/include/QtCore/qscopedpointer.h \
		$(QT_DIR)/include/QtCore/qmetatype.h \
		$(QT_DIR)/include/QtCore/qvarlengtharray.h \
		$(QT_DIR)/include/QtCore/qcontainerfwd.h \
		$(QT_DIR)/include/QtCore/qobject_impl.h \
		$(QT_DIR)/include/QtNetwork/QUdpSocket \
		$(QT_DIR)/include/QtNetwork/qudpsocket.h \
		$(QT_DIR)/include/QtNetwork/qtnetworkglobal.h \
		$(QT_DIR)/include/QtNetwork/qtnetwork-config.h \
		$(QT_DIR)/include/QtNetwork/qabstractsocket.h \
		$(QT_DIR)/include/QtCore/qiodevice.h \
		$(QT_DIR)/include/QtCore/qdebug.h \
		$(QT_DIR)/include/QtCore/qhash.h \
		$(QT_DIR)/include/QtCore/qmap.h \
		$(QT_DIR)/include/QtCore/qtextstream.h \
		$(QT_DIR)/include/QtCore/qlocale.h \
		$(QT_DIR)/include/QtCore/qvariant.h \
		$(QT_DIR)/include/QtCore/qshareddata.h \
		$(QT_DIR)/include/QtCore/qvector.h \
		$(QT_DIR)/include/QtCore/qpoint.h \
		$(QT_DIR)/include/QtCore/qset.h \
		$(QT_DIR)/include/QtCore/qcontiguouscache.h \
		$(QT_DIR)/include/QtCore/qsharedpointer.h \
		$(QT_DIR)/include/QtCore/qsharedpointer_impl.h \
		$(QT_DIR)/include/QtNetwork/qhostaddress.h \
		$(QT_DIR)/include/QtCore/QDebug \
		$(QT_DIR)/include/QtNetwork/QNetworkDatagram \
		$(QT_DIR)/include/QtNetwork/qnetworkdatagram.h \
		$(QT_DIR)/include/QtNetwork/QHostAddress \
		$(QT_DIR)/include/QtNetwork/QNetworkInterface \
		$(QT_DIR)/include/QtNetwork/qnetworkinterface.h \
		$(QT_DIR)/include/QtCore/QCoreApplication \
		$(QT_DIR)/include/QtCore/qcoreapplication.h \
		$(QT_DIR)/include/QtCore/qeventloop.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o gameplay.o gameplay.cpp

main.o: main.cpp $(QT_DIR)/include/QtCore/QCoreApplication \
		$(QT_DIR)/include/QtCore/qcoreapplication.h \
		$(QT_DIR)/include/QtCore/qglobal.h \
		$(QT_DIR)/include/QtCore/qconfig-bootstrapped.h \
		$(QT_DIR)/include/QtCore/qconfig.h \
		$(QT_DIR)/include/QtCore/qtcore-config.h \
		$(QT_DIR)/include/QtCore/qsystemdetection.h \
		$(QT_DIR)/include/QtCore/qprocessordetection.h \
		$(QT_DIR)/include/QtCore/qcompilerdetection.h \
		$(QT_DIR)/include/QtCore/qtypeinfo.h \
		$(QT_DIR)/include/QtCore/qsysinfo.h \
		$(QT_DIR)/include/QtCore/qlogging.h \
		$(QT_DIR)/include/QtCore/qflags.h \
		$(QT_DIR)/include/QtCore/qatomic.h \
		$(QT_DIR)/include/QtCore/qbasicatomic.h \
		$(QT_DIR)/include/QtCore/qatomic_bootstrap.h \
		$(QT_DIR)/include/QtCore/qgenericatomic.h \
		$(QT_DIR)/include/QtCore/qatomic_cxx11.h \
		$(QT_DIR)/include/QtCore/qatomic_msvc.h \
		$(QT_DIR)/include/QtCore/qglobalstatic.h \
		$(QT_DIR)/include/QtCore/qmutex.h \
		$(QT_DIR)/include/QtCore/qnumeric.h \
		$(QT_DIR)/include/QtCore/qversiontagging.h \
		$(QT_DIR)/include/QtCore/qstring.h \
		$(QT_DIR)/include/QtCore/qchar.h \
		$(QT_DIR)/include/QtCore/qbytearray.h \
		$(QT_DIR)/include/QtCore/qrefcount.h \
		$(QT_DIR)/include/QtCore/qnamespace.h \
		$(QT_DIR)/include/QtCore/qarraydata.h \
		$(QT_DIR)/include/QtCore/qstringliteral.h \
		$(QT_DIR)/include/QtCore/qstringalgorithms.h \
		$(QT_DIR)/include/QtCore/qstringview.h \
		$(QT_DIR)/include/QtCore/qstringbuilder.h \
		$(QT_DIR)/include/QtCore/qobject.h \
		$(QT_DIR)/include/QtCore/qobjectdefs.h \
		$(QT_DIR)/include/QtCore/qobjectdefs_impl.h \
		$(QT_DIR)/include/QtCore/qlist.h \
		$(QT_DIR)/include/QtCore/qalgorithms.h \
		$(QT_DIR)/include/QtCore/qiterator.h \
		$(QT_DIR)/include/QtCore/qhashfunctions.h \
		$(QT_DIR)/include/QtCore/qpair.h \
		$(QT_DIR)/include/QtCore/qbytearraylist.h \
		$(QT_DIR)/include/QtCore/qstringlist.h \
		$(QT_DIR)/include/QtCore/qregexp.h \
		$(QT_DIR)/include/QtCore/qstringmatcher.h \
		$(QT_DIR)/include/QtCore/qcoreevent.h \
		$(QT_DIR)/include/QtCore/qscopedpointer.h \
		$(QT_DIR)/include/QtCore/qmetatype.h \
		$(QT_DIR)/include/QtCore/qvarlengtharray.h \
		$(QT_DIR)/include/QtCore/qcontainerfwd.h \
		$(QT_DIR)/include/QtCore/qobject_impl.h \
		$(QT_DIR)/include/QtCore/qeventloop.h \
		gameplay.h \
		$(QT_DIR)/include/QtCore/QObject \
		$(QT_DIR)/include/QtNetwork/QUdpSocket \
		$(QT_DIR)/include/QtNetwork/qudpsocket.h \
		$(QT_DIR)/include/QtNetwork/qtnetworkglobal.h \
		$(QT_DIR)/include/QtNetwork/qtnetwork-config.h \
		$(QT_DIR)/include/QtNetwork/qabstractsocket.h \
		$(QT_DIR)/include/QtCore/qiodevice.h \
		$(QT_DIR)/include/QtCore/qdebug.h \
		$(QT_DIR)/include/QtCore/qhash.h \
		$(QT_DIR)/include/QtCore/qmap.h \
		$(QT_DIR)/include/QtCore/qtextstream.h \
		$(QT_DIR)/include/QtCore/qlocale.h \
		$(QT_DIR)/include/QtCore/qvariant.h \
		$(QT_DIR)/include/QtCore/qshareddata.h \
		$(QT_DIR)/include/QtCore/qvector.h \
		$(QT_DIR)/include/QtCore/qpoint.h \
		$(QT_DIR)/include/QtCore/qset.h \
		$(QT_DIR)/include/QtCore/qcontiguouscache.h \
		$(QT_DIR)/include/QtCore/qsharedpointer.h \
		$(QT_DIR)/include/QtCore/qsharedpointer_impl.h \
		$(QT_DIR)/include/QtNetwork/qhostaddress.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

moc_gameplay.o: moc_gameplay.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_gameplay.o moc_gameplay.cpp

####### Install

install:  FORCE

uninstall:  FORCE

FORCE:

